config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do 
    patch :best_answer, on: :member   
    resources :answers, shallow: true, except: [:index, :show]     
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :author, class_name: 'User'

  validates :body, presence: true

  def best_of?
    self.id == self.question.best_answer_id
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true
  
  has_many :answers, dependent: :destroy
  
  validates :title, :body, presence: true

  def mark_as_best(answer)
		update(best_answer_id: answer.id)
	end
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :author, class_name: 'Answer', foreign_key: 'author_id', dependent: :destroy
  has_many :author, class_name: 'Question', foreign_key: 'author_id', dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def author_of?(resource)
    self.id == resource.author_id
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:new, :create]
  before_action :set_answer, only: [:edit, :update, :destroy]

  def new
    @answer = @question.answers.new
  end
  
  def edit
  end

  def create
    @answer = @question.answers.create(answer_params.merge(author_id: current_user.id))
  end
  
  def update
    if current_user.author_of?(@answer)
      @answer.update(answer_params)
    end
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy     
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
   before_action :load_question, only: [:show, :edit, :update, :destroy, :best_answer]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @best_answer = @question.best_answer
		@answers = @question.answers.where.not(id: @question.best_answer_id)
  end

  def new
    @question = Question.new(author_id: current_user.id)
  end

  def edit
  end

  def create
    @question = Question.new(question_params.merge(author_id: current_user.id))

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(@question) 
      @question.update(question_params)      
    end
  end

  def best_answer
    @answer = Answer.find(params[:answer_id])
    if current_user.author_of?(@question)
       @question.mark_as_best(@answer)
       @best_answer = @question.best_answer
		   @answers = @question.answers.where.not(id: @question.best_answer_id)
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.present?
  = content_tag :div, class: "answer-#{answer.id}"     
    li
      = answer.body
      = render 'answers/control', answer: answer

app/views/answers/_best_answer.html.slim
-if @best_answer.present?
  = content_tag :div, class: "answer-#{@best_answer.id}"     
    li
      = @best_answer.body
      = render 'answers/control', answer: @best_answer

app/views/answers/_control.html.slim
p 
  - if !answer.best_of? && current_user&.author_of?(answer.question)
    = link_to 'Best!', best_answer_question_path(answer.question, answer_id: answer), method: :patch, remote: true
    |  
  - if current_user&.author_of?(answer)
    = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }, local: true      
    |  
    = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true, class: 'delete-answer'
  .answer-errors
    = render 'shared/errors', resource: answer 
  = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    = f.submit 'Save'

app/views/answers/create.js.erb
$('.new-answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers .usual-answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.delete-answer').bind('ajax:success', function(e) {
  $(this).closest('.answer-<%= @answer.id %>').fadeOut().remove();
})

app/views/answers/update.js.erb
$('.answer-<%= @answer.id %> .answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answer-<%= @answer.id %>').replaceWith('<%= j render @answer %>');
<% end %>

app/views/layouts/_header.html.slim
- if user_signed_in? 
  b= current_user.email 
  | |
  = link_to 'Sign out', destroy_user_session_path, method: :delete
- else
  = link_to 'Registration', new_user_registration_path 
  | |
  = link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gethelp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= render 'layouts/header' %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/_form_inline.html.slim
.new-answer-errors
  = render 'shared/errors', resource: @answer
= form_with model: [@question, Answer.new], local: false, class: 'new-answer' do |f|
  = f.label :body
  = f.text_field :body
  = f.submit 

app/views/questions/_question.html.slim
-if question.persisted?
  = content_tag :div, class: "question-#{question.id}"  
    li
      = link_to question.title, question_path(question)
      - if current_user&.author_of?(question)
        p
          = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }, local: true    
          |  
          = link_to "Delete #{question.title}", question_path(question), method: :delete, remote: true, class: 'delete-question'
    .question-errors
      = render 'shared/errors', resource: question
    = form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
      = f.label :title
      = f.text_field :title 
      = f.label :body
      = f.text_area :body 
      = f.submit 'Save'             

app/views/questions/_with_new_answer.html.slim
h1 = @question.title
p = @question.body

p= 'Answers:'
ul 
  .answers  
    .best-answer
      = render partial: 'answers/best_answer', resource: @best_answer
    .usual-answers
      = render partial: 'answers/answer', collection: @answers
- if user_signed_in?  
  p= render 'questions/form_inline'

app/views/questions/best_answer.js.erb
$('.best-answer').html('<%= j render partial: 'answers/best_answer', resource: @best_answer %>');
$('.usual-answers').html('<%= j render partial: 'answers/answer', collection: @answers %>');

app/views/questions/destroy.js.erb
$('.delete-question').bind('ajax:success', function(e) {
  $(this).closest('.question-<%= @question.id %>').fadeOut().remove();
})

app/views/questions/index.html.slim
p
  = link_to 'Ask question', new_question_path
.questions
  = render @questions 

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: [@question], local: true do |f|
  = f.label :title
  = f.text_field :title 
  = f.label :body
  = f.text_area :body 
  = f.submit 'Ask'

app/views/questions/show.html.slim
= render 'questions/with_new_answer'

app/views/questions/update.js.erb
$('.question-<%= @question.id %> .question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question-<%= @question.id %>').replaceWith('<%= j render @question %>');
<% end %>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message